// <auto-generated />
using DataService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataService.Migrations
{
    [DbContext(typeof(GothamContext))]
    partial class GothamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataService.Models.Admins", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DataService.Models.Outlets", b =>
                {
                    b.Property<string>("outletname")
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("foodtype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("landmark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("packets")
                        .HasColumnType("integer");

                    b.Property<string>("streetname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("volunteers")
                        .HasColumnType("integer");

                    b.HasKey("outletname");

                    b.ToTable("Outlets");
                });

            modelBuilder.Entity("DataService.Models.Volunteers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("outletchoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("outletname1")
                        .HasColumnType("text");

                    b.Property<long>("phone")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("outletname1");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("DataService.Models.Volunteers", b =>
                {
                    b.HasOne("DataService.Models.Outlets", "outletname")
                        .WithMany()
                        .HasForeignKey("outletname1");

                    b.Navigation("outletname");
                });
#pragma warning restore 612, 618
        }
    }
}
